"""Convenient top-level exports for domain entities and enums."""

from .dto import CommandSpec, HelpView, PairingOutcome, ReportOutcome
from .exceptions import (
    AccessDeniedError,
    CommandFormatError,
    DomainError,
    NotFoundError,
    OrganizerConfirmationRequiredError,
    RoundsExhaustedError,
    StateError,
    ValidationError,
)
from .models import (
    Game,
    GameReport,
    GameResult,
    Player,
    PlayerStatus,
    Role,
    Round,
    RoundStatus,
    Table,
    Ticket,
    TicketStatus,
    TicketType,
    Tournament,
    TournamentStatus,
    UndoSnapshot,
)

__all__ = [
    "Tournament",
    "TournamentStatus",
    "Player",
    "PlayerStatus",
    "Round",
    "RoundStatus",
    "Table",
    "Game",
    "GameReport",
    "GameResult",
    "Ticket",
    "TicketStatus",
    "TicketType",
    "UndoSnapshot",
    "Role",
    "CommandSpec",
    "HelpView",
    "PairingOutcome",
    "ReportOutcome",
    "DomainError",
    "ValidationError",
    "CommandFormatError",
    "NotFoundError",
    "StateError",
    "AccessDeniedError",
    "RoundsExhaustedError",
    "OrganizerConfirmationRequiredError",
]
